/**********************************************************************
 * Extern for figlet
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var figlet = {
  "text": function () {},
  "textSync": function () {},
  "metadata": function () {},
  "defaults": function () {},
  "parseFont": function () {},
  "loadFont": function () {},
  "loadFontSync": function () {},
  "preloadFonts": function () {}
};
/**********************************************************************
 * End Generated Extern for figlet
/**********************************************************************/